import { getCookie } from "./utils";

const supportedLangObj = {
  am: {
    soon: "በቅርቡ",
    save_as: "እንደ አስቀምጥ",
    download: "አውርድ",
    copy_to_clipboard: "ወደ ቅንጥብ ሰሌዳ ይቅዱ",
    archive: "አስቀምጠን",
    delete: "መሰረዝ",
    unarchive: "ከመጋቢያ ማውጣት",
    rename: "የስም መቀየር",
    discard: "አስወግድ",
    save: "አስቀምጥ",
  },
  ar: {
    soon: "قريبا",
    save_as: "احفظ كـ",
    download: "تنزيل",
    copy_to_clipboard: "نسخ إلى الحافظة",
    archive: "أرشفة",
    delete: "حذف",
    unarchive: "إلغاء الأرشفة",
    rename: "إعادة التسمية",
    discard: "إلغاء",
    save: "حفظ",
  },
  "bg-BG": {
    soon: "Скоро",
    save_as: "Запази като",
    download: "Изтегляне",
    copy_to_clipboard: "Копиране в клипборда",
    archive: "архивиране",
    delete: "изтриване",
    unarchive: "разархивиране",
    rename: "преименуване",
    discard: "отхвърляне",
    save: "запази",
  },
  "bn-BD": {
    soon: "শীঘ্রই",
    save_as: "এই নামে সংরক্ষণ করুন",
    download: "ডাউনলোড",
    copy_to_clipboard: "ক্লিপবোর্ডে কপি করুন",
    archive: "আর্কাইভ করা",
    delete: "মুছে ফেলা",
    unarchive: "আর্কাইভ থেকে বের করা",
    rename: "নাম পরিবর্তন",
    discard: "বাতিল",
    save: "সংরক্ষণ করুন",
  },
  "bs-BA": {
    soon: "Uskoro",
    save_as: "Sačuvaj kao",
    download: "Preuzimanje",
    copy_to_clipboard: "Kopiraj u međuspremnik",
    archive: "arhiviranje",
    delete: "izbrisati",
    unarchive: "dearhivirati",
    rename: "preimenovati",
    discard: "odbaci",
    save: "sačuvaj",
  },
  "ca-ES": {
    soon: "Aviat",
    save_as: "Desa com a",
    download: "Descarregar",
    copy_to_clipboard: "Copia al porta-retalls",
    archive: "arxivar",
    delete: "esborrar",
    unarchive: "desarxivar",
    rename: "canviar el nom",
    discard: "descartar",
    save: "desar",
  },
  "cs-CZ": {
    soon: "Brzy",
    save_as: "Uložit jako",
    download: "Stáhnout",
    copy_to_clipboard: "Kopírovat do schránky",
    archive: "archivování",
    delete: "smazat",
    unarchive: "obnovit z archivu",
    rename: "přejmenovat",
    discard: "zrušit",
    save: "uložit",
  },
  "da-DK": {
    soon: "Snart",
    save_as: "Gem som",
    download: "Download",
    copy_to_clipboard: "Kopiér til udklipsholder",
    archive: "arkivere",
    delete: "slette",
    unarchive: "ophæve arkivering",
    rename: "omdøbe",
    discard: "annuller",
    save: "gem",
  },
  "de-DE": {
    soon: "Bald",
    save_as: "Speichern unter",
    download: "Herunterladen",
    copy_to_clipboard: "In die Zwischenablage kopieren",
    archive: "archivieren",
    delete: "löschen",
    unarchive: "aus dem Archiv holen",
    rename: "umbenennen",
    discard: "verwerfen",
    save: "speichern",
  },
  "el-GR": {
    soon: "Σύντομα",
    save_as: "Αποθήκευση ως",
    download: "Λήψη",
    copy_to_clipboard: "Αντιγραφή στο πρόχειρο",
    archive: "αρχειοθέτηση",
    delete: "διαγραφή",
    unarchive: "επαναφορά από αρχειοθέτηση",
    rename: "μετονομασία",
    discard: "ακύρωση",
    save: "αποθήκευση",
  },
  "en-US": {
    soon: "Soon",
    save_as: "Save as",
    download: "Download",
    copy_to_clipboard: "Copy to Clipboard",
    archive: "archive",
    delete: "delete",
    unarchive: "unarchive",
    rename: "rename",
    discard: "discard",
    save: "save",
  },
  "es-419": {
    soon: "Pronto",
    save_as: "Guardar como",
    download: "Descargar",
    copy_to_clipboard: "Copiar al portapapeles",
    archive: "archivar",
    delete: "eliminar",
    unarchive: "desarchivar",
    rename: "renombrar",
    discard: "descartar",
    save: "guardar",
  },
  "es-ES": {
    soon: "Pronto",
    save_as: "Guardar como",
    download: "Descargar",
    copy_to_clipboard: "Copiar al portapapeles",
    archive: "archivar",
    delete: "eliminar",
    unarchive: "desarchivar",
    rename: "renombrar",
    discard: "descartar",
    save: "guardar",
  },
  "et-EE": {
    soon: "Varsti",
    save_as: "Salvesta nimega",
    download: "Laadi alla",
    copy_to_clipboard: "Kopeeri lõikelauale",
    archive: "arhiivimine",
    delete: "kustuta",
    unarchive: "arhiivist taastada",
    rename: "ümber nimetada",
    discard: "loobu",
    save: "salvesta",
  },
  "fi-FI": {
    soon: "Pian",
    save_as: "Tallenna nimellä",
    download: "Lataa",
    copy_to_clipboard: "Kopioi leikepöydälle",
    archive: "arkistointi",
    delete: "poistaa",
    unarchive: "palauttaa arkistosta",
    rename: "nimeä uudelleen",
    discard: "hylätä",
    save: "tallenna",
  },
  "fr-CA": {
    soon: "Bientôt",
    save_as: "Enregistrer sous",
    download: "Télécharger",
    copy_to_clipboard: "Copier dans le presse-papiers",
    archive: "archiver",
    delete: "supprimer",
    unarchive: "désarchiver",
    rename: "renommer",
    discard: "annuler",
    save: "enregistrer",
  },
  "fr-FR": {
    soon: "Bientôt",
    save_as: "Enregistrer sous",
    download: "Télécharger",
    copy_to_clipboard: "Copier dans le presse-papiers",
    archive: "archiver",
    delete: "supprimer",
    unarchive: "désarchiver",
    rename: "renommer",
    discard: "annuler",
    save: "enregistrer",
  },
  "gu-IN": {
    soon: "શીઘ્ર જ",
    save_as: "તેવું સાચવો",
    download: "ડાઉનલોડ",
    copy_to_clipboard: "ક્લિપબોર્ડમાં કૉપિ કરો",
    archive: "આર્કાઇવ કરવું",
    delete: "હટાવવું",
    unarchive: "અભિલેખાગારમાંથી બહાર લાવવું",
    rename: "નામ બદલવું",
    discard: "રદ કરો",
    save: "સાચવો",
  },
  "hi-IN": {
    soon: "जल्द ही",
    save_as: "इस रूप में सहेजें",
    download: "डाउनलोड",
    copy_to_clipboard: "क्लिपबोर्ड पर कॉपी करें",
    archive: "आर्काइव करना",
    delete: "हटाएं",
    unarchive: "संग्रह से निकालें",
    rename: "नाम बदलें",
    discard: "रद्द करें",
    save: "सहेजें",
  },
  "hr-HR": {
    soon: "Uskoro",
    save_as: "Spremi kao",
    download: "Preuzimanje",
    copy_to_clipboard: "Kopiraj u međuspremnik",
    archive: "arhiviranje",
    delete: "izbrisati",
    unarchive: "vratiti iz arhive",
    rename: "preimenovati",
    discard: "odbaci",
    save: "spremi",
  },
  "hu-HU": {
    soon: "Hamarosan",
    save_as: "Mentés másként",
    download: "Letöltés",
    copy_to_clipboard: "Másolás vágólapra",
    archive: "archiválás",
    delete: "töröl",
    unarchive: "visszaállítás az archívumból",
    rename: "átnevezés",
    discard: "elvetés",
    save: "mentés",
  },
  "hy-AM": {
    soon: "Շուտով",
    save_as: "Պահել որպես",
    download: "Ներբեռնել",
    copy_to_clipboard: "Պատճենել սեղմատախտակին",
    archive: "արխիվացում",
    delete: "ջնջել",
    unarchive: "վերականգնել արխիվից",
    rename: "վերանվանել",
    discard: "հրաժարվել",
    save: "պահպանել",
  },
  "id-ID": {
    soon: "Segera",
    save_as: "Simpan sebagai",
    download: "Unduh",
    copy_to_clipboard: "Salin ke papan klip",
    archive: "mengarsipkan",
    delete: "hapus",
    unarchive: "batalkan arsip",
    rename: "ubah nama",
    discard: "batalkan",
    save: "simpan",
  },
  "is-IS": {
    soon: "Bráðum",
    save_as: "Vista sem",
    download: "Niðurhal",
    copy_to_clipboard: "Afrita í klippiborð",
    archive: "að skrá í skjalasafn",
    delete: "eyða",
    unarchive: "afskrá úr skjalasafni",
    rename: "endurnefna",
    discard: "hætta við",
    save: "vista",
  },
  "it-IT": {
    soon: "Presto",
    save_as: "Salva con nome",
    download: "Scaricare",
    copy_to_clipboard: "Copia negli appunti",
    archive: "archiviazione",
    delete: "elimina",
    unarchive: "ripristina dall'archivio",
    rename: "rinomina",
    discard: "annulla",
    save: "salva",
  },
  "ja-JP": {
    soon: "近日中",
    save_as: "名前を付けて保存",
    download: "ダウンロード",
    copy_to_clipboard: "クリップボードにコピー",
    archive: "アーカイブすること",
    delete: "削除",
    unarchive: "アーカイブを解除",
    rename: "名前を変更",
    discard: "破棄",
    save: "保存",
  },
  "ka-GE": {
    soon: "მალე",
    save_as: "შენახვა როგორც",
    download: "ჩამოტვირთვა",
    copy_to_clipboard: "კოპირება ბუფერში",
    archive: "დაარქივება",
    delete: "წაშლა",
    unarchive: "არქივიდან აღდგენა",
    rename: "სახელის შეცვლა",
    discard: "გაუქმება",
    save: "შენახვა",
  },
  kk: {
    soon: "Жақында",
    save_as: "Басқаша сақтау",
    download: "Жүктеу",
    copy_to_clipboard: "Буферге көшіру",
    archive: "мұрағаттау",
    delete: "жою",
    unarchive: "мұрағаттан шығару",
    rename: "қайта атау",
    discard: "бас тарту",
    save: "сақтау",
  },
  "kn-IN": {
    soon: "ಶೀಘ್ರದಲ್ಲೇ",
    save_as: "ಹೆಸರುಗಳನ್ನು ಉಳಿಸು",
    download: "ಡೌನ್‌ಲೋಡ್",
    copy_to_clipboard: "ಕ್ಲಿಪ್‌ಬೋರ್ಡ್‌ಗೆ ಪ್ರತಿಲಿಪಿ ಮಾಡಿ",
    archive: "ಆರ್ಕೈವ್ ಮಾಡುವುದು",
    delete: "ಅಳಿಸಿ",
    unarchive: "ಆರ್ಕೈವ್ ತೆಗೆದುಹಾಕಿ",
    rename: "ಮರುಹೆಸರಿಸು",
    discard: "ರದ್ದುಮಾಡಿ",
    save: "ಉಳಿಸಿ",
  },
  "ko-KR": {
    soon: "곧",
    save_as: "다른 이름으로 저장",
    download: "다운로드",
    copy_to_clipboard: "클립보드에 복사",
    archive: "보관하기",
    delete: "삭제",
    unarchive: "보관 해제",
    rename: "이름 변경",
    discard: "취소",
    save: "저장",
  },
  lt: {
    soon: "Netrukus",
    save_as: "Įrašyti kaip",
    download: "Atsisiųsti",
    copy_to_clipboard: "Kopijuoti į mainų sritį",
    archive: "archyvavimas",
    delete: "ištrinti",
    unarchive: "išarchyvuoti",
    rename: "pervadinti",
    discard: "atsisakyti",
    save: "išsaugoti",
  },
  "lv-LV": {
    soon: "Drīzumā",
    save_as: "Saglabāt kā",
    download: "Lejupielādēt",
    copy_to_clipboard: "Kopēt starpliktuvē",
    archive: "arhivēšana",
    delete: "dzēst",
    unarchive: "atjaunot no arhīva",
    rename: "pārsaukt",
    discard: "atcelt",
    save: "saglabāt",
  },
  "mk-MK": {
    soon: "Набргу",
    save_as: "Зачувај како",
    download: "Преземи",
    copy_to_clipboard: "Копирај во привремената меморија",
    archive: "архивирање",
    delete: "избриши",
    unarchive: "деархивирај",
    rename: "преименувај",
    discard: "откажи",
    save: "зачувај",
  },
  ml: {
    soon: "വെറും കുറച്ച് ദിവസങ്ങൾ",
    save_as: "ഇത് പോലെ സംരക്ഷിക്കുക",
    download: "ഡൗൺലോഡ്",
    copy_to_clipboard: "ക്ലിപ്പ്ബോർഡിലേക്ക് പകർത്തുക",
    archive: "ആർക്കൈവിൽ ഇടൽ",
    delete: "നീക്കം ചെയ്യുക",
    unarchive: "ആർക്കൈവിൽ നിന്ന് പുറത്ത് എടുക്കുക",
    rename: "പുനർനാമകരണം",
    discard: "റദ്ദാക്കുക",
    save: "സേവ് ചെയ്യുക",
  },
  mn: {
    soon: "Удахгүй",
    save_as: "Гэж хадгалах",
    download: "Татах",
    copy_to_clipboard: "Түр санах ойд хуулбарлах",
    archive: "архивлах",
    delete: "устгах",
    unarchive: "архиваас гаргах",
    rename: "нэрийг өөрчлөх",
    discard: "цуцлах",
    save: "хадгалах",
  },
  "mr-IN": {
    soon: "लवकरच",
    save_as: "या नावाने साठवा",
    download: "डाउनलोड",
    copy_to_clipboard: "क्लिपबोर्डवर कॉपी करा",
    archive: "आर्काइव्ह करणे",
    delete: "हटवा",
    unarchive: "संग्रहितमधून काढा",
    rename: "पुन्हा नाव द्या",
    discard: "रद्द करा",
    save: "जतन करा",
  },
  "ms-MY": {
    soon: "Segera",
    save_as: "Simpan sebagai",
    download: "Muat turun",
    copy_to_clipboard: "Salin ke papan keratan",
    archive: "mengarkibkan",
    delete: "padam",
    unarchive: "buka arkib",
    rename: "namakan semula",
    discard: "batal",
    save: "simpan",
  },
  "my-MM": {
    soon: "မကြာခင်",
    save_as: "အဖြစ် သိမ်းမည်",
    download: "ဒေါင်းလုပ်",
    copy_to_clipboard: "ကလစ်ဘုတ်သို့ ကော်ပီလုပ်ပါ",
    archive: "အော်ကိုထည့်ခြင်း",
    delete: "ဖျက်ပါ",
    unarchive: "ဖိုင်မှထုတ်မည်",
    rename: "နာမည်ပြောင်းရန်",
    discard: "ဖျက်သိမ်းပါ",
    save: "သိမ်းဆည်းပါ",
  },
  "nb-NO": {
    soon: "Snart",
    save_as: "Lagre som",
    download: "Last ned",
    copy_to_clipboard: "Kopier til utklippstavle",
    archive: "arkivering",
    delete: "slette",
    unarchive: "avarkiver",
    rename: "gi nytt navn",
    discard: "avbryt",
    save: "lagre",
  },
  "nl-NL": {
    soon: "Binnenkort",
    save_as: "Opslaan als",
    download: "Downloaden",
    copy_to_clipboard: "Kopiëren naar klembord",
    archive: "archiveren",
    delete: "verwijderen",
    unarchive: "de-archiveren",
    rename: "hernoemen",
    discard: "annuleren",
    save: "opslaan",
  },
  pa: {
    soon: "ਜਲਦੀ ਹੀ",
    save_as: "ਇਸ ਤਰ੍ਹਾਂ ਸੇਵ ਕਰੋ",
    download: "ਡਾਊਨਲੋਡ",
    copy_to_clipboard: "ਕਲਿੱਪਬੋਰਡ ਤੇ ਕਾਪੀ ਕਰੋ",
    archive: "ਆਰਕਾਈਵ ਕਰਨਾ",
    delete: "ਹਟਾਓ",
    unarchive: "ਆਰਕਾਈਵ ਤੋਂ ਬਾਹਰ ਕਰੋ",
    rename: "ਮੁੜ ਨਾਮਕਰਨ ਕਰੋ",
    discard: "ਰੱਦ ਕਰੋ",
    save: "ਸੰਭਾਲੋ",
  },
  "pl-PL": {
    soon: "Wkrótce",
    save_as: "Zapisz jako",
    download: "Pobierz",
    copy_to_clipboard: "Kopiuj do schowka",
    archive: "archiwizowanie",
    delete: "usuń",
    unarchive: "przywróć z archiwum",
    rename: "zmień nazwę",
    discard: "anuluj",
    save: "zapisz",
  },
  "pt-BR": {
    soon: "Em breve",
    save_as: "Salvar como",
    download: "Baixar",
    copy_to_clipboard: "Copiar para a área de transferência",
    archive: "arquivar",
    delete: "excluir",
    unarchive: "desarquivar",
    rename: "renomear",
    discard: "descartar",
    save: "salvar",
  },
  "pt-PT": {
    soon: "Em breve",
    save_as: "Guardar como",
    download: "Descarregar",
    copy_to_clipboard: "Copiar para a área de transferência",
    archive: "arquivar",
    delete: "eliminar",
    unarchive: "desarquivar",
    rename: "renomear",
    discard: "descartar",
    save: "guardar",
  },
  "ro-RO": {
    soon: "În curând",
    save_as: "Salvează ca",
    download: "Descărcare",
    copy_to_clipboard: "Copiază în clipboard",
    archive: "arhivare",
    delete: "șterge",
    unarchive: "dezarchiva",
    rename: "redenumire",
    discard: "anulare",
    save: "salvare",
  },
  "ru-RU": {
    soon: "Скоро",
    save_as: "Сохранить как",
    download: "Скачать",
    copy_to_clipboard: "Копировать в буфер обмена",
    archive: "архивирование",
    delete: "удалить",
    unarchive: "разархивировать",
    rename: "переименовать",
    discard: "отменить",
    save: "сохранить",
  },
  "sk-SK": {
    soon: "Čoskoro",
    save_as: "Uložiť ako",
    download: "Stiahnuť",
    copy_to_clipboard: "Kopírovať do schránky",
    archive: "archivovanie",
    delete: "vymazať",
    unarchive: "obnoviť z archívu",
    rename: "premenovať",
    discard: "zrušiť",
    save: "uložiť",
  },
  "sl-SI": {
    soon: "Kmalu",
    save_as: "Shrani kot",
    download: "Prenesi",
    copy_to_clipboard: "Kopiraj v odložišče",
    archive: "arhiviranje",
    delete: "izbrisati",
    unarchive: "obnoviti iz arhiva",
    rename: "preimenovati",
    discard: "prekliči",
    save: "shrani",
  },
  "so-SO": {
    soon: "Dhawaan",
    save_as: "Keydso sidii",
    download: "Soo dejiso",
    copy_to_clipboard: "Nuqul ka samee sabuuradda",
    archive: "keydinta",
    delete: "tirtir",
    unarchive: "ka saar kaydka",
    rename: "magac bixin cusub",
    discard: "tirtir",
    save: "badbaadi",
  },
  "sq-AL": {
    soon: "Së shpejti",
    save_as: "Ruaj si",
    download: "Shkarko",
    copy_to_clipboard: "Kopjo në kujtesë",
    archive: "arkivimi",
    delete: "fshi",
    unarchive: "ç’arkivoni",
    rename: "riemërtoj",
    discard: "anulo",
    save: "ruaj",
  },
  "sr-RS": {
    soon: "Ускоро",
    save_as: "Сачувај као",
    download: "Преузми",
    copy_to_clipboard: "Копирај у привремену меморију",
    archive: "архивирање",
    delete: "избрисати",
    unarchive: "деархивирати",
    rename: "преименовати",
    discard: "откажи",
    save: "сачувај",
  },
  "sv-SE": {
    soon: "Snart",
    save_as: "Spara som",
    download: "Ladda ner",
    copy_to_clipboard: "Kopiera till urklipp",
    archive: "arkivering",
    delete: "radera",
    unarchive: "avarkivera",
    rename: "döp om",
    discard: "avbryt",
    save: "spara",
  },
  "sw-TZ": {
    soon: "Hivi karibuni",
    save_as: "Hifadhi kama",
    download: "Pakua",
    copy_to_clipboard: "Nakili kwenye ubao wa kunakili",
    archive: "kuhifadhi",
    delete: "futa",
    unarchive: "toa kutoka kwenye hifadhi",
    rename: "badilisha jina",
    discard: "futa",
    save: "hifadhi",
  },
  "ta-IN": {
    soon: "விரைவில்",
    save_as: "இதுபோல சேமி",
    download: "பதிவிறக்கம்",
    copy_to_clipboard: "பட்டிகையில் நகலெடுக்கவும்",
    archive: "ஆர்கைவ் செய்யுதல்",
    delete: "அழி",
    unarchive: "ஆவணப்படுத்தலிலிருந்து வெளியேற்றுக",
    rename: "மறுபெயரிடுக",
    discard: "ரத்து செய்யவும்",
    save: "சேமிக்கவும்",
  },
  "te-IN": {
    soon: "త్వరలో",
    save_as: "ఇలా సేవ్ చేయి",
    download: "డౌన్‌లోడ్",
    copy_to_clipboard: "క్లిప్‌బోర్డ్‌కు కాపీ చేయండి",
    archive: "ఆర్కైవ్ చేయడం",
    delete: "తొలగించు",
    unarchive: "ఆర్కైవ్ నుండి తొలగించు",
    rename: "పేరు మార్చు",
    discard: "రద్దు చేయి",
    save: "సేవ్ చేయి",
  },
  "th-TH": {
    soon: "เร็ว ๆ นี้",
    save_as: "บันทึกเป็น",
    download: "ดาวน์โหลด",
    copy_to_clipboard: "คัดลอกไปที่คลิปบอร์ด",
    archive: "การเก็บถาวร",
    delete: "ลบ",
    unarchive: "ยกเลิกการเก็บถาวร",
    rename: "เปลี่ยนชื่อ",
    discard: "ยกเลิก",
    save: "บันทึก",
  },
  tl: {
    soon: "Malapit na",
    save_as: "I-save bilang",
    download: "I-download",
    copy_to_clipboard: "Kopyahin sa clipboard",
    archive: "pag-archive",
    delete: "tanggalin",
    unarchive: "tanggalin mula sa archive",
    rename: "palitan ng pangalan",
    discard: "i-discard",
    save: "i-save",
  },
  "tr-TR": {
    soon: "Yakında",
    save_as: "Farklı kaydet",
    download: "İndir",
    copy_to_clipboard: "Panoya kopyala",
    archive: "arşivleme",
    delete: "sil",
    unarchive: "arşivden çıkar",
    rename: "yeniden adlandır",
    discard: "iptal et",
    save: "kaydet",
  },
  "uk-UA": {
    soon: "Незабаром",
    save_as: "Зберегти як",
    download: "Завантажити",
    copy_to_clipboard: "Копіювати в буфер обміну",
    archive: "архівування",
    delete: "видалити",
    unarchive: "розархівувати",
    rename: "перейменувати",
    discard: "скасувати",
    save: "зберегти",
  },
  ur: {
    soon: "جلد",
    save_as: "اس نام سے محفوظ کریں",
    download: "ڈاؤن لوڈ",
    copy_to_clipboard: "کلپ بورڈ پر کاپی کریں",
    archive: "آرکائیو کرنا",
    delete: "حذف کریں",
    unarchive: "آرکائیو سے نکالیں",
    rename: "نام تبدیل کریں",
    discard: "منسوخ کریں",
    save: "محفوظ کریں",
  },
  "vi-VN": {
    soon: "Sắp tới",
    save_as: "Lưu thành",
    download: "Tải xuống",
    copy_to_clipboard: "Sao chép vào bộ nhớ tạm",
    archive: "lưu trữ",
    delete: "xóa",
    unarchive: "bỏ lưu trữ",
    rename: "đổi tên",
    discard: "hủy bỏ",
    save: "lưu",
  },
  "zh-CN": {
    soon: "即将推出",
    save_as: "另存为",
    download: "下载",
    copy_to_clipboard: "复制到剪贴板",
    archive: "归档",
    delete: "删除",
    unarchive: "取消存档",
    rename: "重命名",
    discard: "取消",
    save: "保存",
  },
  "zh-HK": {
    soon: "即將推出",
    save_as: "另存為",
    download: "下載",
    copy_to_clipboard: "複製到剪貼簿",
    archive: "存檔",
    delete: "刪除",
    unarchive: "取消封存",
    rename: "重新命名",
    discard: "取消",
    save: "儲存",
  },
  "zh-TW": {
    soon: "即將推出",
    save_as: "另存為",
    download: "下載",
    copy_to_clipboard: "複製到剪貼簿",
    archive: "存檔",
    delete: "刪除",
    unarchive: "取消封存",
    rename: "重新命名",
    discard: "取消",
    save: "儲存",
  },
};

/**
 * @type {Record<
 *    'soon'             |
 *    'save_as'          |
 *    'download'         |
 *    'copy_to_clipboard'|
 *    'archive'          |
 *    'delete'           |
 *    'unarchive'        |
 *    'rename'           |
 *    'discard'          |
 *    'save', string>}
 */
export default (() => {
  const preferedLang = JSON.parse(localStorage.getItem("oai/apps/locale")) || getCookie("oai-locale");

  if (preferedLang === "dev") return supportedLangObj["en-US"];

  if (preferedLang) return supportedLangObj[preferedLang];
  else {
    const browserPreferedLangauge = [navigator.language] || navigator.languages;

    for (let [k, v] of Object.entries(supportedLangObj)) {
      k = k.split("-")[0];

      if (browserPreferedLangauge.some((item) => item.startsWith(k))) return v;
    }
  }

  return supportedLangObj["en-US"];
})();
